title: Portafolio de GARAZI lASA
author: Garazi Lasa
email: garazilasa@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Ongi etorri web orri berri honetara. Espero dut bertan aurkitutako informazioa baliagarria izatea.

# social links
twitter_username: garazilasa # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  garazilasa # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: true # cámbialo a false para eliminar los extractos de la página principal
theme: minima
